name: Deploy Static Web App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_341DD48E54A741F2BECE57A53BB989AA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C07EDA8842D64E3280A36BF597939AFB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D93ECF6E2C264EDFA2EB755339B5A91D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-Gulfam-NUM-BSCS-2023-31'
          slot-name: 'Production'
          package: .
